name: Generate 3D Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa todos os dias à meia-noite
  workflow_dispatch:     # Permite executar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate 3D Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Eric-Giannetti
          outputs: |
            ./profile-3d-contrib/github-contribution-grid-snake.svg
            ./profile-3d-contrib/github-contribution-grid-snake-dark.svg

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "update contribution snake 🐍" || echo "no changes"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
