name: Generate 3D Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # roda diariamente
  workflow_dispatch: # executável manualmente

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./profile-3d-contrib/github-contribution-grid-snake.svg
            ./profile-3d-contrib/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "generate 3d contribution snake" || echo "No changes to commit"
          git push
